spring:
  profiles:
    active: pro


  jackson:
    default-property-inclusion: non_null

  jpa:
    show-sql: true
  jmx:
    default-domain: wd-jmx

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource

#    # 初始化，最小，最大连接数
#    initialSize: 3
#    minidle: 3
#    maxActive: 18
#    # 获取数据库连接等待的超时时间
#    maxWait: 60000
#    # 配置多久进行一次检测，检测需要关闭的空闲连接 单位毫秒
#    timeBetweenEvictionRunsMillis: 60000
#    validationQuery: SELECT 1 FROM dual
#    # 配置监控统计拦截的filters,去掉后，监控界面的sql无法统计

    filters: stat
    maxActive: 2
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

server:
  port: 80




