spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: wzy1gqqbuu
    url: jdbc:mysql://49.232.232.173:3306/wd?useUnicode=true&characterEncoding=UTF-8&useSSL=false


redis:
  host: 49.232.232.173
  port: 6379
  timeout: 10
  password: wzy1gqqbuu
  poolMaxTotal: 1000
  poolMaxIdle: 500