spring:
  profiles:
    active: dev


  jackson:
    default-property-inclusion: non_null


#redis.host=10.110.3.62
#redis.port=6379
#redis.timeout=10
#redis.password=123456
#redis.poolMaxTotal=1000
#redis.poolMaxIdle=500