spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: wzy1gqqbuu
    url: jdbc:mysql://localhost:3306/wd?useUnicode=true&characterEncoding=UTF-8&useSSL=false
