spring:
  profiles:
    active: dev


  jackson:
    default-property-inclusion: non_null

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

redis:
  host: 192.168.0.138
  port: 6379
  timeout: 10
  password: wzy1gqqbuu
  poolMaxTotal: 1000
  poolMaxIdle: 500